name: Build

on: push

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]
        os: [macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.3

      - name: Commit
        run: |
          git config --global user.name 'Wheel bot'
          git config --global user.email '<>'
          git add wheelhouse/*.whl
          git commit -m "Bot: Add built wheels" -m "[skip ci]"
          git push
